"""P3.5 知识库审核状态

Revision ID: 4e4a29dd8a69
Revises: 641c363008f5
Create Date: 2026-09-03 10:25:48.803364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4a29dd8a69'
down_revision: Union[str, Sequence[str], None] = '641c363008f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('knowledge', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('knowledge', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_knowledge_reviewer_id', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_constraint('fk_knowledge_reviewer_id', type_='foreignkey')
    op.drop_column('knowledge', 'reviewed_at')
    op.drop_column('knowledge', 'reviewer_id')
    op.drop_column('knowledge', 'status')
    # ### end Alembic commands ###
