"""P6.4 Recording加customer_id

Revision ID: c253025d8d53
Revises: 4e4a29dd8a69
Create Date: 2026-09-03 14:17:40.077064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c253025d8d53'
down_revision: Union[str, Sequence[str], None] = '4e4a29dd8a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注：knowledge.reviewer_id 的 FK 已在 P3.5 库中实际存在，此处不再重复添加
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recordings_customer_id', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recordings_customer_id', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
